### ISSUE TITLE
想改成 2 人的该咋改呀，6人的训练不动

### ISSUE THREAD

**Issue by Sober-Chen** [Cothrax/deepfool#1]

**Comment by 177715031** [comment]
请问一下我这里有一些bug不知道怎么解决，首先是吗，neuron_poker环境，然后是

class DataLoaderX(DataLoader):

    def __iter__(self):
        return BackgroundGenerator(super().__iter__())
的 BackgroundGenerator出错

**Comment by Cothrax** [comment]
其实这个repo的可扩展性比较差，只建议参考思路...
如果一定要把这个repo改成2人的话，至少要做：
1. 改动 `cfr_py/params.py` 中的 `NUM_PLAYER`
2. 改动神经网络的结构从6人改成2人

neuron_poker的环境来自于这个repo：[https://github.com/dickreuter/neuron_poker](https://github.com/dickreuter/neuron_poker)

BackgroundGenerator的问题具体是什么？可能需要取消 `utils.py` 第11行的注释。

**Comment by kingzhanggengit** [comment]
人数修改为2，需要修改神经网络的结构，仅仅需要修改输入端就可以了吧

**Comment by Cothrax** [comment]
> 人数修改为2，需要修改神经网络的结构，仅仅需要修改输入端就可以了吧

应该是的
